name: Update Dining Hours JSON

on:
  schedule:
    - cron: "0 10 * * *"  # Scheduled time (6 a.m. EDT, 10 a.m. UTC)
  workflow_dispatch:  # Allows manual trigger for testing

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run dining hours script
      run: python updatedining.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add database/dining.json
        git commit -m "Daily update of dining hours JSON"
        git push
