name: Update Dining Hours JSON

on:
  schedule:
    - cron: "0 10 * * *"  # Runs every day at 10:00 UTC (6:00 a.m. Eastern Time)

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run dining hours script
      run: python path/to/your_script.py  # Replace with the actual path to your script

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add database/dining.json
        git commit -m "Daily update of dining hours JSON"
        git push
